### ISSUE TITLE
fatal error: unexpectedly found nil while unwrapping an Optional value

### ISSUE THREAD

**Issue by Sethu171988** [BenjaminPrieur/IOStickyHeader#16]
I downloaded the 1.0.0 version and tried running the sample code on simulator iOS 10 swift 3 and I got the below error"fatal error: unexpectedly found nil while unwrapping an Optional value"

Any help is much appreciated!

**Comment by codover** [comment]
I have the same issue at IOStickyHeaderFlowLayout.swift line 75.

```
...
if currentAttribute == nil || (indexPath as NSIndexPath).row > (currentAttribute as AnyObject).indexPath.row {
...
```

Not happening if Collection View has only 1 section and 1 element in it. But when I use your "section" array, boom.

**Comment by giovanny1307** [comment]
I have the same issue, but i dont understand why the example project works, i just copied the code and in my project the library throws this error.

**Comment by Geeo** [comment]
Same error here (line 75)

`if currentAttribute == nil || (indexPath as NSIndexPath).row > (currentAttribute as AnyObject).indexPath.row {`

More specifically, error is happening here, the second time we go in the function :

`(currentAttribute as AnyObject).indexPath.row)`

This because `(currentAttribute as AnyObject).indexPath` is nil

WORKAROUND :

Replace line 75 with :

`if (currentAttribute == nil || ((currentAttribute as AnyObject).indexPath != nil && (indexPath as NSIndexPath).row > (currentAttribute as AnyObject).indexPath.row)) {
`

**Comment by BenjaminPrieur** [comment]
Thanks @Geeo for your solution.
New version (1.0.1) is available with the fix

**Comment by giovanny1307** [comment]
Thanks @Geeo  and @BenjaminPrieur Thank you for your great work on the lib.

**Comment by Geeo** [comment]
Thanks @BenjaminPrieur essentially :) i just fix a bug of a great lib :)
